server:
  port: ${SERVER_PORT:8082}
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/customerdb}
    username: ${SPRING_DATASOURCE_USERNAME:customer}
    password: ${SPRING_DATASOURCE_PASSWORD:customer}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH_ISSUER_URI:http://keycloak:8080/realms/shop}
          jwk-set-uri: ${OAUTH_JWK_SET_URI:http://keycloak:8080/realms/shop/protocol/openid-connect/certs}
app:
  security-disabled: ${APP_SECURITY_DISABLED:false}
